Repository CA-G12/team3-bookStore, pull requests merged in 2022-08, with the labels that each got.

#2 create the file structre relates #1
  .gitignore
  package-lock.json
  package.json
  public/index.html
  public/js/clientSideValidation.js
  public/js/dom.js
  public/pages/cart.html
  public/pages/errors/404.html
  public/pages/errors/500.html
  public/pages/login.html
  public/pages/signup.html
  public/style/main.css
  server/app.js
  server/controllers/index.js
  server/database/config/connection.js
  server/database/config/init.js
  server/database/config/init.sql
  server/database/queries/getAllBooksQuery.js
  server/index.js
  server/middlewares/isLogged.js
  tests/test.js
Labels: done

#5 database connetion relates #4
  .env
  .gitignore
  server/database/config/connection.js
Labels: approved

#7 create the database structure relates #3
  .gitignore
  package-lock.json
  server/database/config/connection.js
  server/database/config/init.js
  server/database/config/init.sql
  server/database/config/tempCodeRunnerFile.js
  server/router/index.js
Labels: awiting-review

#8 create server and port listen to 8000
  .gitignore
  package-lock.json
  package.json
  server/app.js
  server/index.js
Labels: awiting-review

#10 fix the sql schema realtes #9
  server/database/config/init.sql
Labels: awiting-review

#13 add login form relates #12
  public/index.html
  public/pages/login.html
  server/app.js
  server/controllers/index.js
  server/database/config/connection.js
  server/database/queries/loginQuery.js
Labels: approved

#16 create hash
  package-lock.json
  package.json
  server/controllers/addUser.js
  server/controllers/hashPassword.js
  server/controllers/index.js
  server/database/queries/addUser.js
  server/router/index.js
Labels: approved

#18 login password comfirmation realtes #17
  server/controllers/addUser.js
  server/controllers/hashPassword.js
  server/controllers/loginVerify.js
  server/database/queries/loginQuery.js
Labels: approved

#21 login confirmation relates #20
  server/controllers/loginVerify.js
Labels: approved

#22 craete signup validation server side and change the email in users t…
  package-lock.json
  package.json
  server/controllers/hashPassword.js
  server/controllers/signupValidation.js
  server/database/config/init.sql
Labels: approved

#27 create cart page html , css relates #24
  public/pages/cart.html
  public/style/cart.css
Labels: approved

#28 create the home page and style it relates #25
  public/index.html
  public/style/index.css
Labels: awiting-review

#29 add login page html and style relates #26
  public/js/loginPage.js
  public/pages/login.html
  public/style/loginPage.css
Labels: awiting-review

#30 create singup page and style
  public/pages/signup.html
  public/style/singUp.css
Labels: done, approved

#32 fix some style relates #31
  public/pages/signup.html
  public/style/loginPage.css
  public/style/singUp.css
Labels: approved

#34 create the user login validation relates #33
  public/index.html
  public/js/dom.js
  server/app.js
  server/controllers/checkLoggedUser.js
  server/controllers/index.js
  server/controllers/loginVerify.js
  server/controllers/logout.js
  server/router/index.js
Labels: approved

#38 get cart data from database relates #35
  public/js/cart.js
  public/pages/cart.html
  server/controllers/getCart.js
  server/controllers/index.js
  server/database/queries/getCart.js
  server/database/queries/index.js
  server/router/index.js
Labels: approved

#39 login relates #37
  public/js/loginVail.js
  public/pages/login.html
  public/style/loginPage.css
  server/controllers/loginVerify.js
Labels: awiting-review

#41 handle error in form
  public/js/singup.js
  public/pages/signup.html
  public/style/singUp.css
  server/controllers/hashPassword.js
Labels: approved

#42 cretae the generate books card function and make th get all bi=ooks q…
  public/index.html
  public/js/dom.js
  public/style/index.css
  server/controllers/getAllBooks.js
  server/controllers/index.js
  server/database/queries/getAllBooksQuery.js
  server/database/queries/index.js
  server/router/index.js
Labels: done, approved

#43 get cart from database and put header in cart page relates #35
  public/js/cart.js
  public/pages/cart.html
  public/style/cart.css
  server/database/queries/getCart.js
Labels: awiting-review

#45 handle the routs
  public/index.html
  public/js/cart.js
  public/js/dom.js
  public/js/loginVail.js
  public/pages/cart.html
  server/controllers/addToCart.js
  server/controllers/cartPage.js
  server/controllers/deleteCartItem.js
  server/controllers/index.js
  server/controllers/loginVerify.js
  server/database/config/connection.js
  server/database/queries/addToCartQuery.js
  server/database/queries/deleteCartItemQuery.js
  server/database/queries/getCart.js
  server/database/queries/index.js
  server/middlewares/isLogged.js
  server/router/index.js
Labels: approved
